import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'About | Next App',
  description: 'Generated by create next app',
};

export default function About() {
  return (
    <div>
      <h1>About</h1>
      <span>Select layout</span>
    </div>
  );
}
